### ISSUE TITLE
Obfuscating number attribute produces malformed json

### ISSUE THREAD

**Issue by vitgorbunov** [robtimus/obfuscation-json#1]
Obfuscating json like this {"pin" : 1234} produces {"pin" : ****}
Which is invalid json format since **** is not enclosed in double quotes.
It causes issues if later I try to process this json.
I wonder if it's intended behaviour of this library or it's a bug?

**Comment by robtimus** [comment]
That's intentional. The goal of this library is mostly obfuscation during logging or other forms of storage as a string. It was never intended to produce valid JSON.

**Comment by vitgorbunov** [comment]
Even for cases like logging I'd have to worry that log analyzer (kibana or similar or any handmade one) can handle malformed json (e.g. if I want to filter by some other unobfuscated data in the same json)
But thanks for the response, I will need to look for something else.

**Comment by robtimus** [comment]
Maybe I can add an option that will turn all obfuscated values into strings. Let me see what's possible.

**Comment by robtimus** [comment]
I've just released version [1.1](https://github.com/robtimus/obfuscation-json/releases/tag/1.1) that adds support for producing valid JSON.

**Comment by vitgorbunov** [comment]
Thanks a lot!

**Comment by robtimus** [comment]
You're welcome.
